[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/logo-white.png"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/emblem.png"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/email-logo.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
