'use client';

import React, { useState } from 'react';
import type { EffectivenessData } from '../ConferenceEffectivenessModal';
import { StrategyWeightNotice } from './StrategyWeightNotice';
import { ConferenceRankingsModal } from './ConferenceRankingsModal';

function fmt$(n: unknown) { const v = n == null ? null : Number(n); if (v == null || isNaN(v)) return '—'; return '$' + Math.round(v).toLocaleString(); }
const scoreColor = (score: number) => score >= 90 ? '#059669' : score >= 75 ? '#1B76BC' : score >= 60 ? '#d97706' : score >= 50 ? '#f97316' : '#dc2626';
const scoreGrade = (score: number) => score >= 90 ? 'Exceptional efficiency' : score >= 75 ? 'Strong efficiency' : score >= 60 ? 'Acceptable efficiency' : score >= 50 ? 'Weak efficiency' : 'Inefficient';
const INTERPRETATION_ROWS = [
  { range: '90–100', rating: 'Exceptional', meaning: 'Exceptional cost efficiency — strong pipeline return and low cost per engagement' },
  { range: '75–89', rating: 'Strong', meaning: 'Strong efficiency; near-optimal cost-to-outcome ratio' },
  { range: '60–74', rating: 'Acceptable', meaning: 'Acceptable efficiency; some room for improvement' },
  { range: '50–59', rating: 'Weak', meaning: 'Weak efficiency; review cost allocation and engagement strategy' },
  { range: '< 50', rating: 'Inefficient', meaning: 'Significant underperformance relative to benchmarks' },
];

function RepMetricCell({ value, score, tier }: { value: unknown; score: unknown; tier: unknown }) { const v = value == null ? null : Number(value); const s = score == null ? null : Number(score); const t = tier == null ? '' : String(tier); if (v == null || isNaN(v)) return <span className="text-gray-300">—</span>; return <span className="font-medium text-gray-700">{fmt$(v)}{s != null && <span className="ml-1 text-xs font-normal"><span className="font-semibold" style={{ color: scoreColor(s) }}>{s}</span>{t && <span className="text-gray-400"> · {t}</span>}</span>}</span>; }

export function OperationalROITab({ data }: { data: EffectivenessData }) {
  const { operational, ces } = data; const costs = operational.cost_efficiency as Record<string, any>; const repRows = (operational.rep_cost_efficiency ?? []) as Record<string, unknown>[];
  const waterfall = (operational as any).cost_efficiency_waterfall; const spendAllocation = (operational as any).spend_allocation; const ladder = (operational as any).cost_per_outcome_ladder; const breakEven = (operational as any).break_even_view; const quadrant = (operational as any).cost_efficiency_quadrant;
  const [showInterpretation, setShowInterpretation] = useState(false); const [showRankings, setShowRankings] = useState(false);
  const componentEntries = [{ label: 'Pipeline Influence per $1k spent', score: costs.pipeline_influence_score }, { label: 'Cost per Company Engaged', score: costs.company_engaged_score }, { label: 'Cost per Meeting Held', score: costs.meeting_held_score }].filter(c => c.score != null);
  const strongest = componentEntries.slice().sort((a,b)=>Number(b.score)-Number(a.score))[0]; const weakest = componentEntries.slice().sort((a,b)=>Number(a.score)-Number(b.score))[0];
  const driverText = strongest && weakest ? `Primary driver: ${strongest.label.toLowerCase()} offset weaker ${weakest.label.toLowerCase()}.` : null;
  return <div className="p-6"><div className="grid grid-cols-1 lg:grid-cols-2 gap-6">{/* keep existing top */}
  <div>{/* omitted for brevity in instruction: retained style */}
    <div className="flex items-center justify-between mb-3"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide">Cost Efficiency</h3></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-3"><div className="sm:col-span-2 rounded-xl p-4" style={{ backgroundColor: scoreColor(Number(costs.cost_efficiency_score ?? 0)) + '15', borderLeft: `4px solid ${scoreColor(Number(costs.cost_efficiency_score ?? 0))}` }}><div className="flex items-start justify-between mb-2"><div className="text-xs font-bold uppercase tracking-wide text-gray-500">Cost Efficiency Score</div><button type="button" onClick={() => setShowInterpretation(v => !v)} className="text-gray-400 hover:text-brand-secondary" aria-label="Score interpretation">i</button></div><div className="text-4xl font-bold" style={{ color: scoreColor(Number(costs.cost_efficiency_score ?? 0)) }}>{Number(costs.cost_efficiency_score ?? 0)}</div><div className="text-xs font-semibold" style={{ color: scoreColor(Number(costs.cost_efficiency_score ?? 0)) }}>{scoreGrade(Number(costs.cost_efficiency_score ?? 0))}</div><StrategyWeightNotice applied={true} strategyLabel={String((data as any).conference_strategy?.display_name || 'Not set')} />{driverText && <div className="mt-2 text-xs text-gray-500">{driverText}</div>}</div>
      <button type="button" onClick={() => setShowRankings(true)} className="sm:col-span-1 rounded-xl border border-gray-200 bg-gray-50 p-4 flex flex-col items-center justify-center"><div className="text-xs text-gray-500">Efficiency Rank</div><div className="text-3xl font-bold text-brand-secondary">#{Number(operational.conf_efficiency_rank ?? 1)}</div><div className="text-xs text-gray-400">of {Number(operational.conf_efficiency_total ?? 1)} conferences</div></button></div>
    <div className="space-y-2">{[{ label: 'Cost per Company Engaged', value: fmt$(costs.cost_per_company_engaged) }, { label: 'Cost per Meeting Held', value: fmt$(costs.cost_per_meeting_held) }, { label: 'Cost per ICP Interaction', value: fmt$(costs.cost_per_icp_interaction) }, { label: 'Pipeline Influence per $1k Spent', value: fmt$(costs.pipeline_influence_per_1k_spent) }].map(({ label, value }) => <div key={label} className="rounded-lg border border-gray-100 bg-gray-50 p-3 flex justify-between"><div className="text-xs text-gray-500">{label}</div><div className="text-sm font-bold text-brand-secondary">{value}</div></div>)}</div>
  </div><div><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-3">Cost Efficiency by Rep</h3><div className="hidden sm:block overflow-x-auto rounded-xl border border-gray-100"><table className="w-full text-xs"><thead><tr className="bg-gray-50"><th className="text-left px-3 py-2">Rep</th><th className="text-right px-3 py-2">Pipeline / $1k</th><th className="text-right px-3 py-2">Cost / Company</th><th className="text-right px-3 py-2">Cost / Meeting</th></tr></thead><tbody>{repRows.map((r,i)=><tr key={i}><td className="px-3 py-2">{String(r.rep ?? '—')}</td><td className="px-3 py-2 text-right"><RepMetricCell value={r.rep_pipeline_influence_per_1000} score={r.rep_pipeline_score} tier={r.rep_pipeline_score_tier} /></td><td className="px-3 py-2 text-right"><RepMetricCell value={r.rep_cost_per_company_engaged} score={r.rep_company_score} tier={r.rep_company_score_tier} /></td><td className="px-3 py-2 text-right"><RepMetricCell value={r.rep_cost_per_meeting_held} score={r.rep_meeting_score} tier={r.rep_meeting_score_tier} /></td></tr>)}</tbody></table></div></div></div>

<div className="mt-6 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-5 gap-4">
<div className="xl:col-span-2 rounded-xl border border-gray-200 bg-white p-4"><h4 className="text-sm font-semibold text-brand-primary mb-2">Cost Efficiency Waterfall</h4>{waterfall?.components?.length ? waterfall.components.map((c: any)=><div key={c.key} className="mb-2"><div className="flex justify-between text-xs"><span className="text-gray-500">{c.label}</span><span className="font-semibold text-brand-secondary">{c.weighted_contribution?.toFixed?.(1)}</span></div><div className="h-2 bg-gray-100 rounded"><div className="h-2 rounded bg-brand-secondary" style={{ width: `${Math.max(2, Math.min(100, Number(c.weighted_contribution ?? 0)))}%` }} /></div></div>) : <p className="text-xs text-gray-400 italic">Not enough component data to show score contribution.</p>}</div>
<div className="xl:col-span-3 rounded-xl border border-gray-200 bg-white p-4"><h4 className="text-sm font-semibold text-brand-primary mb-2">Spend Allocation Breakdown</h4>{spendAllocation?.categories?.length ? <div className="space-y-2">{spendAllocation.categories.map((c: any)=><div key={c.id} className="text-xs flex justify-between"><span className="text-gray-500">{c.label}</span><span className="font-semibold text-gray-700">{fmt$(c.amount)} · {Math.round(Number(c.percent ?? 0))}%</span></div>)}<div className="text-xs text-gray-500 pt-2 border-t">Top cost driver: {spendAllocation.top_cost_driver?.label ?? '—'}</div></div> : <p className="text-xs text-gray-400 italic">No spend allocation detail available for this conference.</p>}</div>
<div className="xl:col-span-2 rounded-xl border border-gray-200 bg-white p-4"><h4 className="text-sm font-semibold text-brand-primary mb-2">Cost per Outcome Ladder</h4>{ladder?.metrics?.length ? ladder.metrics.map((m: any)=><div key={m.key} className="flex justify-between text-xs py-1 border-b border-gray-50"><span className="text-gray-500">{m.label}</span><span className="font-semibold text-gray-700">{m.available ? fmt$(m.value) : '—'}</span></div>) : <p className="text-xs text-gray-400 italic">Not enough outcome data to calculate per-outcome cost metrics.</p>}</div>
<div className="xl:col-span-3 rounded-xl border border-gray-200 bg-white p-4"><h4 className="text-sm font-semibold text-brand-primary mb-2">Break-even / Pipeline Coverage</h4>{breakEven?.required_pipeline ? <div className="space-y-1 text-xs"><div className="flex justify-between"><span className="text-gray-500">Total Event Spend</span><span className="font-semibold">{fmt$(breakEven.total_spend)}</span></div><div className="flex justify-between"><span className="text-gray-500">Required Pipeline</span><span className="font-semibold">{fmt$(breakEven.required_pipeline)}</span></div><div className="flex justify-between"><span className="text-gray-500">Actual Pipeline Influence</span><span className="font-semibold">{fmt$(breakEven.actual_pipeline_influence)}</span></div><div className="flex justify-between"><span className="text-gray-500">Coverage Ratio</span><span className="font-semibold">{breakEven.pipeline_coverage_ratio?.toFixed?.(1)}x</span></div></div> : <p className="text-xs text-gray-400 italic">Break-even view unavailable because spend or return target data is missing.</p>}</div>
<div className="xl:col-span-5 grid grid-cols-1 xl:grid-cols-5 gap-4"><div className="xl:col-span-1 rounded-xl border border-gray-200 bg-white p-3 aspect-square"><h4 className="text-xs font-semibold text-brand-primary mb-2">Cost Efficiency Quadrant</h4><p className="text-[11px] text-gray-400">{quadrant?.conferences?.length > 1 ? `Compared conferences: ${quadrant.conferences.length}` : 'Not enough historical conference data to render a portfolio comparison.'}</p></div><div className="xl:col-span-4 rounded-xl border border-gray-200 bg-white p-4 text-xs text-gray-500">Portfolio context uses median thresholds for cost per company engaged and pipeline influence per $1k spent. Current conference is highlighted in the plotted dataset when available.</div></div>
</div>

<div className="mt-4 text-xs text-gray-400 text-right">Conference Effectiveness Score: <span className="font-semibold" style={{ color: ces.score >= 70 ? '#059669' : ces.score >= 40 ? '#d97706' : '#dc2626' }}>{ces.score}/100</span></div>
{showRankings && <ConferenceRankingsModal title="Cost Efficiency Rankings" currentConferenceId={Number(data.conference.id ?? 0)} onClose={() => setShowRankings(false)} />}
</div>;
}
