'use client';

import type { EffectivenessData } from '../ConferenceEffectivenessModal';

function fmtPct(v: number | null | undefined) { return v == null || isNaN(v) ? '—' : `${Math.round(v)}%`; }
function fmtNum(v: number | null | undefined) { return v == null || isNaN(v) ? '—' : Math.round(v).toLocaleString(); }
function fmt$(v: number | null | undefined) { return v == null || isNaN(v) ? '—' : `$${Math.round(v).toLocaleString()}`; }
function color(score: number | null | undefined) { const s = Number(score ?? 0); if (s >= 90) return '#059669'; if (s >= 75) return '#1B76BC'; if (s >= 60) return '#d97706'; if (s >= 50) return '#f97316'; return '#dc2626'; }
const riskBg: Record<string, string> = { healthy: 'bg-green-50 text-green-700', watch: 'bg-amber-50 text-amber-700', risk: 'bg-red-50 text-red-700', unavailable: 'bg-gray-100 text-gray-500' };

export function SalesExecutionTab({ data }: { data: EffectivenessData }) {
  const sx = data.sales_execution as any;
  const sv = (data as any).sales_visuals;
  const reps = (data.pipeline.rep_attribution ?? []) as Record<string, unknown>[];
  if (!sx) return <div className="p-6 text-sm text-gray-500">Sales execution data unavailable.</div>;

  return <div className="p-6 space-y-6">
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
      <div className="sm:col-span-2 rounded-xl p-4" style={{ backgroundColor: color(sx.sales_effectiveness_score) + '15', borderLeft: `4px solid ${color(sx.sales_effectiveness_score)}` }}>
        <div className="text-xs font-bold uppercase tracking-wide text-gray-500">Sales Effectiveness Score</div>
        <div className="flex items-end gap-1"><div className="text-4xl font-bold" style={{ color: color(sx.sales_effectiveness_score) }}>{sx.sales_effectiveness_score ?? '—'}</div><div className="text-sm text-gray-400 mb-0.5">/100</div></div>
        <div className="text-xs font-semibold" style={{ color: color(sx.sales_effectiveness_score) }}>{sx.sales_effectiveness_interpretation ?? 'Not scored'}</div>
        <div className="mt-3 pt-3 border-t border-current border-opacity-20 space-y-1.5">{Object.entries(sx.components ?? {}).map(([key, comp]: any) => <div key={key} className="flex justify-between text-xs"><span className="text-gray-500">{key.replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())} <span className="text-gray-300">({Math.round((Number(comp.weight ?? 0)) * 100)}%)</span></span><span className="font-semibold" style={{ color: color(comp.score) }}>{comp.score ?? '—'} <span className="text-gray-400">· {comp.tier ?? '—'}</span></span></div>)}</div>
      </div>
      <div className="rounded-xl border border-gray-200 bg-gray-50 p-4 flex flex-col items-center justify-center text-center"><div className="text-xs text-gray-500 font-medium mb-1">Sales Execution Rank</div>{sx.sales_execution_rank ? <><div className="text-3xl font-bold text-brand-secondary">#{sx.sales_execution_rank}</div><div className="text-xs text-gray-400">of {sx.sales_execution_rank_total} conferences</div></> : <><div className="text-sm font-semibold text-gray-500">Not ranked</div><div className="text-xs text-gray-400">Ranking requires at least two scored conferences.</div></>}</div>
    </div>

    <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[['Meeting Hold Rate', fmtPct(sx.kpis.meeting_hold_rate)], ['Follow-up Completion', fmtPct(sx.kpis.followup_completion_rate)], ['Follow-up Attachment', fmtPct(sx.kpis.followup_attachment_rate)], ['Pipeline / Meeting', fmt$(sx.kpis.pipeline_per_meeting)], ['Pipeline / Company', fmt$(sx.kpis.pipeline_per_company)], ['Avg Influenced Deal', fmt$(sx.kpis.average_influenced_deal_size)]].map(([l, v]) => <div key={String(l)} className="rounded-lg border border-gray-100 bg-gray-50 p-3"><div className="text-xs text-gray-500">{l}</div><div className="text-lg font-bold text-brand-secondary">{v}</div></div>)}</div>

    <div className="card p-5 overflow-x-auto"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-3">Rep Performance</h3><table className="w-full text-xs min-w-[980px]"><thead><tr className="text-gray-400 uppercase border-b border-gray-100"><th className="text-left pb-2">Rep</th><th className="text-right pb-2">Held</th><th className="text-right pb-2">Sched.</th><th className="text-right pb-2">Hold %</th><th className="text-right pb-2">Touchpoints</th><th className="text-right pb-2">Companies</th><th className="text-right pb-2">Pipeline</th><th className="text-right pb-2">Pipeline/Meeting</th><th className="text-right pb-2">Contribution</th><th className="text-right pb-2">Coaching Flag</th></tr></thead><tbody className="divide-y divide-gray-50">{reps.map((r, i) => { const held = Number(r.meetings_held ?? 0); const sched = Number(r.meetings_scheduled ?? 0); const hold = sched > 0 ? held / sched * 100 : null; const tp = Number(r.touchpoints ?? 0); const pi = Number(r.pipeline_influence_attributed ?? 0); const contrib = Number(r.contribution_pct ?? 0); const flag = hold != null && hold < 50 ? 'Low meeting hold rate' : contrib > 25 ? 'Top contributor' : 'Under-leveraged'; return <tr key={i}><td className="py-2 font-medium">{String(r.rep ?? '—')}</td><td className="text-right">{held}</td><td className="text-right">{sched}</td><td className="text-right">{fmtPct(hold)}</td><td className="text-right">{tp}</td><td className="text-right">{fmtNum(Number(r.unique_companies_met ?? 0))}</td><td className="text-right font-semibold text-brand-secondary">{fmt$(pi)}</td><td className="text-right">{fmt$(held > 0 ? pi / held : null)}</td><td className="text-right">{fmtPct(contrib)}</td><td className="text-right">{flag}</td></tr>; })}</tbody></table></div>

    <div className="grid grid-cols-1 lg:grid-cols-5 gap-4">
      <div className="card p-4 lg:col-span-3"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-2">Rep Execution Quadrant</h3><p className="text-xs text-gray-500 mb-2">Sales Activity vs Pipeline Influence</p>{(sv?.rep_execution_quadrant?.reps ?? []).length === 0 ? <p className="text-xs text-gray-400">Not enough rep-level activity and pipeline data to plot this view.</p> : <div className="grid grid-cols-2 gap-2 text-xs">{sv.rep_execution_quadrant.reps.map((r: any) => <div key={r.rep_id} className="rounded border border-gray-100 p-2 bg-gray-50"><div className="font-semibold text-gray-700">{r.rep_name}</div><div>{fmtNum(r.sales_activities)} activities</div><div>{fmt$(r.pipeline_influence)} pipeline</div><div className="text-gray-500">{r.quadrant?.replace(/_/g, ' ')}</div></div>)}</div>}</div>
      <div className="card p-4 lg:col-span-2"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-2">Follow-up Funnel</h3>{sv?.followup_funnel ? <div className="space-y-2 text-xs">{[['Sales Activities', sv.followup_funnel.sales_activities], ['Meetings Held', sv.followup_funnel.meetings_held], ['Follow-ups Created', sv.followup_funnel.followups_created], ['Follow-ups Completed', sv.followup_funnel.followups_completed]].map(([l, v]) => <div key={String(l)} className="flex justify-between"><span className="text-gray-500">{l}</span><span className="font-semibold text-gray-700">{fmtNum(Number(v))}</span></div>)}<div className="pt-2 border-t text-gray-600">Completion: <span className="font-semibold">{fmtPct(sv.followup_funnel.followup_completion_rate)}</span></div></div> : <p className="text-xs text-gray-400">No follow-up data available for this conference.</p>}</div>

      <div className="card p-4 lg:col-span-2"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-2">Pipeline Contribution by Rep</h3>{(sv?.pipeline_contribution_by_rep?.reps ?? []).map((r: any) => <div key={r.rep_id} className="mb-2"><div className="flex justify-between text-xs"><span>{r.rep_name}</span><span>{fmt$(r.pipeline_influence)} · {fmtPct(r.contribution_percent)}</span></div><div className="w-full h-2 bg-gray-100 rounded"><div className="h-2 rounded bg-brand-secondary" style={{ width: `${Math.min(Number(r.contribution_percent ?? 0), 100)}%` }} /></div></div>)}</div>
      <div className="card p-4 lg:col-span-3"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-2">Activity Mix by Rep</h3>{(sv?.activity_mix_by_rep?.reps ?? []).map((r: any) => <div key={r.rep_id} className="mb-2 text-xs"><div className="flex justify-between"><span>{r.rep_name}</span><span>{r.sales_activities} total</span></div><div className="flex h-2 rounded overflow-hidden bg-gray-100"><div className="bg-blue-500" style={{ width: `${r.sales_activities ? (r.meetings_held / r.sales_activities) * 100 : 0}%` }} /><div className="bg-cyan-400" style={{ width: `${r.sales_activities ? (r.touchpoints_logged / r.sales_activities) * 100 : 0}%` }} /></div></div>)}</div>

      <div className="card p-4 lg:col-span-3"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-2">Rep Score Breakdown</h3>{(sv?.rep_score_breakdown?.reps ?? []).map((r: any) => <div key={r.rep_id} className="mb-2 text-xs"><div className="font-medium">{r.rep_name}</div><div className="flex h-2 rounded overflow-hidden bg-gray-100"><div className="bg-blue-500" style={{ width: `${Number(r.meeting_execution_score ?? 0) / 5}%` }} /><div className="bg-amber-400" style={{ width: `${Number(r.pipeline_influence_execution_score ?? 0) / 5}%` }} /><div className="bg-green-500" style={{ width: `${Number(r.rep_productivity_score ?? 0) / 5}%` }} /></div></div>)}</div>
      <div className="card p-4 lg:col-span-2"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-2">Pipeline per Activity Benchmark</h3>{sv?.pipeline_per_activity_gauge ? <><div className="text-lg font-bold text-brand-secondary">{fmt$(sv.pipeline_per_activity_gauge.pipeline_per_sales_activity)}</div><div className="text-xs text-gray-500">Expected: {fmt$(sv.pipeline_per_activity_gauge.expected_pipeline_per_sales_activity)}</div><div className="w-full h-2 bg-gray-100 rounded mt-2"><div className="h-2 rounded bg-brand-secondary" style={{ width: `${Math.min(Number(sv.pipeline_per_activity_gauge.score ?? 0), 100)}%` }} /></div><div className="text-xs text-gray-500 mt-1">{sv.pipeline_per_activity_gauge.interpretation ?? 'Expected pipeline per activity benchmark is not configured.'}</div></> : <p className="text-xs text-gray-400">Expected pipeline per activity benchmark is not configured.</p>}</div>

      <div className="card p-4 lg:col-span-5"><h3 className="font-semibold text-brand-primary text-sm uppercase tracking-wide mb-2">Sales Execution Risk Heatmap</h3><div className="overflow-x-auto"><table className="w-full text-xs min-w-[780px]"><thead><tr className="text-gray-500 border-b"><th className="text-left py-2">Rep</th>{['Low Hold Rate', 'Low Follow-up Completion', 'Low Target Engagement', 'Low Pipeline/Activity', 'Low Activity'].map(h => <th key={h} className="text-left py-2">{h}</th>)}</tr></thead><tbody>{(sv?.sales_execution_risk_heatmap?.reps ?? []).map((r: any) => <tr key={r.rep_id} className="border-b border-gray-50"><td className="py-2 font-medium">{r.rep_name}</td>{Object.values(r.risks).map((v: any, i) => <td key={i}><span className={`px-2 py-0.5 rounded text-[11px] ${riskBg[String(v)]}`}>{String(v)}</span></td>)}</tr>)}</tbody></table></div></div>
    </div>
  </div>;
}
