export const companyPools = {
  healthcare: {
    prospects: [
      // Major health systems & IDNs
      'Mayo Clinic', 'Cleveland Clinic', 'Johns Hopkins Medicine', 'Mass General Brigham',
      'Kaiser Permanente', 'CommonSpirit Health', 'Ascension Health', 'HCA Healthcare',
      'Advocate Health', 'Providence Health', 'AdventHealth', 'UPMC', 'Intermountain Health',
      'Northwell Health', 'Atrium Health', 'Memorial Hermann', 'Ochsner Health',
      'Sanford Health', 'SSM Health', 'Baylor Scott & White Health', 'Tenet Healthcare',
      'Community Health Systems', 'LifePoint Health', 'Beaumont Health', 'Henry Ford Health',
      'Geisinger Health', 'UnityPoint Health', 'OhioHealth', 'Prisma Health',
      'WakeMed Health', 'Banner Health', 'Dignity Health', 'SCL Health', 'Allina Health',
      'Fairview Health Services', 'Centura Health', 'Essentia Health', 'Gundersen Health',
      'Marshfield Clinic Health System', 'Froedtert Health', 'Advocate Aurora Health',
      'RWJBarnabas Health', 'Hackensack Meridian Health', 'Hartford HealthCare',
      'Yale New Haven Health', 'UMass Memorial Health', 'Beth Israel Lahey Health',
      'Lifespan', 'South Shore Health', 'Cape Cod Healthcare', 'Steward Health Care',
      'Bon Secours Mercy Health', 'Trinity Health', 'Mercy Health', 'OSF HealthCare',
      'CHRISTUS Health', 'Covenant Health', 'Sutter Health', 'Scripps Health',
      'Sharp HealthCare', 'Cedars-Sinai Health System', 'UCLA Health', 'UCSF Health',
      'Stanford Health Care', "Dignity Health – St. Joseph's", 'PeaceHealth', 'MultiCare Health',
      'Providence St. Joseph', 'Swedish Health Services', 'Virginia Mason Franciscan',
      'CHI Franciscan', 'Legacy Health', 'OHSU Health', 'Avera Health', 'Monument Health',
      'Hy-Vee Health', 'Bryan Health', 'Mary Lanning Healthcare', 'CHI Health',
    ],
    partners: [
      'Accenture Health', 'Deloitte Health Sciences', 'McKinsey Healthcare Practice',
      'Boston Consulting Group Health', 'Guidehouse', 'Chartis Group', 'Kaufman Hall',
      'Sg2', 'Advisory Board', 'Health Catalyst', 'Evolent Health', 'Optum Advisory',
      'Huron Consulting Group', 'Impact Advisors', 'Nordic Consulting', 'Pivot Point Consulting',
      'Cumberland Consulting Group', 'Freed Associates', 'Hayes Management Consulting',
      'Point B', 'Slalom Health', 'West Monroe Health', 'Nuvolo Health', 'Tegria',
      'Avaap', 'Navisite Health', 'Clearsense', 'Arcadia', 'Innovalon', 'Privia Health',
    ],
    vendors: [
      'Epic Systems', 'Oracle Cerner', 'Meditech', 'Allscripts', 'athenahealth',
      'eClinicalWorks', 'NextGen Healthcare', 'GE Healthcare IT', 'Philips Healthcare IT',
      'Siemens Healthineers', 'Stryker', 'Teladoc Health', 'Veradigm', 'Change Healthcare',
      'Inovalon', 'Nuvolo', 'ServiceNow Healthcare', 'Microsoft Health', 'AWS Health',
      'Google Cloud Healthcare', 'Salesforce Health Cloud', 'Workday Healthcare',
      'Kronos/UKG Healthcare', 'API Healthcare', 'Symplr', 'Hyland Healthcare',
      'MedAssets', 'Parallon', 'Vizient', 'Premier Inc.', 'HealthStream',
    ],
  },

  senior_living: {
    prospects: [
      'Brookdale Senior Living', 'Sunrise Senior Living', 'Five Star Senior Living',
      'Atria Senior Living', 'Benchmark Senior Living', 'Erickson Senior Living',
      'Holiday Retirement', 'Watermark Retirement', 'Vi Living', 'LCS',
      'Lifespace Communities', 'Acts Retirement', 'Westminster Communities',
      'Senior Lifestyle Corporation', 'Integral Senior Living', 'Civitas Senior Living',
      'Discovery Senior Living', 'Solera Senior Living', 'Sagora Senior Living',
      'Frontier Management', 'Anthem Memory Care', 'Grace Management',
      'Spectrum Retirement', 'The Arbor Company', 'Meridian Senior Living',
      'Pathway Senior Living', 'Eclipse Senior Living', 'Commonwealth Senior Living',
      'Priority Life Care', 'Sinceri Senior Living', 'Juniper Communities',
      'Brightview Senior Living', 'Hawthorn Senior Living', 'Leisure Care',
      'Somerby Senior Living', 'Maplewood Senior Living', 'Artis Senior Living',
      'Seasons Living', 'Chancellor Health Care', 'American Senior Living',
      'Greystone Healthcare Management', 'Elmcroft Senior Living', 'Vitality Senior Living',
      'StoneGate Senior Living', 'Legend Senior Living', 'Bethesda Senior Living',
      'Heritage Senior Living', 'Prestige Senior Living', 'The Goodman Group',
      'Senior Care Centers', 'IntegraCare',
    ],
    partners: [
      'Ziegler', 'Lument', 'KeyBank Senior Housing', 'Greystone', 'CBRE Senior Housing',
      'JLL Senior Living', 'Senior Living Investment Brokerage', 'Blueprint Healthcare',
      'Healthpeak Properties', 'Welltower', 'Ventas', 'NIC (National Investment Center)',
      'LeadingAge', 'Argentum', 'Holleran Consulting', 'corecubed',
      'Ryan, LLC Senior Housing', 'Dixon Hughes Goodman', 'RSM Senior Care',
      'BDO Senior Living', 'Plante Moran Senior Care', 'Wipfli Senior Living',
    ],
    vendors: [
      'PointClickCare', 'MatrixCare', 'Yardi Senior Living', 'RealPage Senior Living',
      'AL Advantage', 'Eldermark', 'OnShift', 'Aline', 'Enquire CRM',
      'Senior Insight', 'WelcomeHome CRM', 'Lifespark', 'iCare Health',
      'Caremerge', 'Seniorly', 'A Place for Mom', 'Caring.com',
      'Conviva Senior Care', 'SimpleLTC', 'American HealthTech',
      'HHAeXchange', 'CarePredict', 'K4Connect', 'Cubigo', 'Halo Smart Nurse',
    ],
  },

  generic_b2b: {
    prospects: [
      'Axiom Systems', 'Crestview Solutions', 'Meridian Group', 'Vantage Partners',
      'Pinnacle Dynamics', 'Crossroads Industries', 'Summit Holdings', 'Horizon Enterprises',
      'Keystone Ventures', 'Cascade Technologies', 'Ridgeline Capital', 'Ironwood Services',
      'Clearwater Group', 'Stonehurst Partners', 'Woodbridge Consulting', 'Redwood Analytics',
      'Northbridge Associates', 'Lakewood Industries', 'Edgewood Solutions', 'Belmont Group',
      'Harborview Partners', 'Bayshore Capital', 'Hillcrest Advisors', 'Silvergate Dynamics',
      'Westbrook Systems', 'Riverstone Holdings', 'Greenfield Ventures', 'Bridgewater Industries',
      'Fairfield Enterprises', 'Collingwood Partners', 'Broadstone Group', 'Elmwood Solutions',
      'Foxwood Analytics', 'Glenwood Capital', 'Highgate Partners', 'Maplecrest Advisors',
      'Northgate Systems', 'Oakwood Holdings', 'Pineridge Group', 'Quaker Dynamics',
      'Ridgewood Ventures', 'Sherwood Industries', 'Timberline Solutions', 'Underhill Associates',
    ],
    partners: [
      'Apex Consulting Group', 'Bravura Advisory', 'Constellation Partners', 'Delphi Advisors',
      'Elevate Consulting', 'Frontier Advisors', 'Genesis Partners', 'Hallmark Consulting',
      'Insight Advisory Group', 'Juniper Consulting',
    ],
    vendors: [
      'Atlas Software', 'Blueprint Technologies', 'Catalyst Platforms', 'Datastax Solutions',
      'Edge Computing Co', 'FlowTech Systems', 'Grid Analytics', 'Helix Data',
      'Integral Cloud', 'Junction AI',
    ],
  },
};

export type Vertical = keyof typeof companyPools;
export type CompanyRole = 'prospects' | 'partners' | 'vendors';
